version: '3.8'

services:
  stream_receiver:
    build: ./stream_receiver
    environment:
      - RTMP_URL=rtmp://0.0.0.0/live/stream
      - FRAME_OUTPUT=/frames
    volumes:
      - ./shared/frames:/frames
    restart: unless-stopped

  detector:
    build: ./detector
    environment:
      - FRAME_INPUT=/frames
    volumes:
      - ./shared/frames:/frames
    restart: unless-stopped
